### ISSUE TITLE
Rage Fighter Upgrade Master skill Weapon Mastery Client Ben collapse

### ISSUE THREAD

**Issue by tangyi90** [kessiler/muOnline-season6#22]

**Comment by tangyi90** [comment]
We can solve this problem？

**Comment by kessiler** [comment]
@tangyi90 Have a problem or not?

**Comment by tangyi90** [comment]
There is a problem.
I do not know the point where the issue closed

**Comment by kessiler** [comment]
@tangyi90 can you put screenshots about that?

**Comment by tangyi90** [comment]
![1](https://cloud.githubusercontent.com/assets/14145481/9807322/215da694-5884-11e5-84c1-8343056789c7.jpg)
![2](https://cloud.githubusercontent.com/assets/14145481/9807342/61cc6c42-5884-11e5-9ca9-8894a824d1f3.jpg)
![3](https://cloud.githubusercontent.com/assets/14145481/9807347/852c1912-5884-11e5-9878-fbb1181f126d.jpg)

**Comment by sonnickoo** [comment]
What was the solution?

**Comment by kessiler** [comment]
@sonnickoo in my client doesn't exists that problem.
